name: New Prod Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.head_ref }}
      - name: Build the Docker image
        run: |
          echo "production build started"
          COMMIT_ID=`echo $(git rev-parse HEAD)`
          COMMIT_ID_SHORT=`echo $(git rev-parse HEAD) | cut -c1-7`
          # docker login docker.pkg.github.com -u anontyro -p ${{secrets.ACTIONS_PASSWORD}}
          # IMAGE_TAG=docker.pkg.github.com/anontyro/mysite-2.0/my-site:$COMMIT_ID_SHORT
          docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}          
          IMAGE_TAG=alexjohnwilkinson/star-wars:$COMMIT_ID_SHORT
          IMAGE_TAG_LATEST=alexjohnwilkinson/star-wars:latest
          echo "new image tag created $IMAGE_TAG"
          docker build --file Dockerfile --tag $IMAGE_TAG --tag $IMAGE_TAG_LATEST .
          docker push $IMAGE_TAG_LATEST
          echo "production build: $IMAGE_TAG successfully created"